# Create a new client API key which can be found under "Account Settings" then " API Credentials", the URL path should be https://pterodactyl.test/account/api.
pterodactyl_api_key: "ptlc_xxx"
pterodactyl_client_api_base_url: "https://pterodactyl.test/api/client" # No trailing slash
servers:
  # "survival" is the name of the configured server in your "velocity.toml" file
  # "abc" should be replaced with the identifier of your server in Pterodactyl
  # this can be found in the URL such as: https://pterodactyl.test/server/:server_id
  # where ":server_id" is the identifier of the server
  survival: "abc"
waiting_server_name: "limbo" # "limbo" is the name of the configured server in your "velocity.toml" file
maximum_ping_duration: 60 # in seconds
shutdown_after_duration: 3600 # in seconds
